import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased bg-slate-900 leading-relaxed text-slate-400 antialiased selection:bg-primary selection:text-primary expansion-alids-init`}
      >
        <main className="min-h-screen mx-auto max-w-screen-xl px-6 py-12 font-sans md:px-12 md:py-16 lg:py-0">
          <a href="#content" className="absolute left-0 top-0 block -translate-x-full rounded bg-gradient-to-br from-primary via-blue-500 to-purple-600 px-4 py-3 text-sm font-bold uppercase tracking-widest text-white focus-visible:translate-x-0">Skip to Content</a>
          <section className="lg:flex lg:justify-between lg:gap-4">
            <Header />
            
            <main id="content" className="pt-24 lg:w-[52%] lg:py-24">
              {children}
            </main>
          </section>
        </main>
      </body>
    </html>
  );
}
